AWSTemplateFormatVersion: 2010-09-09
Description: Celeste Service

Parameters:
  ServiceName:
    Type: String
    Default: celeste
  Environment:
    Type: String
    Default: local
  DatabaseBugs:
    Type: String
    Default: bugs
  DatabaseAccounts:
    Type: String
    Default: accounts
  DatabaseAgents:
    Type: String
    Default: Agents
  QueueName:
    Type: String
    Default: bugs
  BuildBucket:
    Type: String
    Default: celeste
  BuildKey:
    Type: String
    Default: celeste-local.zip

Resources:
  ServiceARN:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join: ['-', [Ref ServiceName, role, Ref Environment]]
      AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principle:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
      Policies:
        - PolicyName: celesteLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                Resource:
                  Fn::Join: [':', [arn, aws, sqs, Ref AWS::Region, Ref AWS::AccountId, Ref MainQueue]]
              - Effect: Allow
                Action:
                  - sqs:ReveiveMessage
                Resource:
                  Fn::Join: [':', [arn, aws, sqs, Ref AWS::Region, Ref AWS::AccountId, Ref DeadLetterQueue]]
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  Fn::Join: [':', [arn, aws, dynamodb, Ref AWS::Region, Ref::AccountId, Ref DatabaseBugs]]
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  Fn::Join: [':', [arn, aws, dynamodb, Ref AWS::Region, Ref::AccountId, Ref DatabaseAccounts]]
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  Fn::Join: [':', [arn, aws, dynamodb, Ref AWS::Region, Ref::AccountId, Ref DatabaseAgents]]

  MainQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 5
      QueueName:
        Fn::Join: ['-', [Ref ServiceName, MainQueue, Ref Environemnt]]
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join: ['-', [Ref ServiceName, DeadLetterQueue, Ref Environment]]

  BugsDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: Ref DatabaseBugs
  AccountsDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: Ref DatabaseAccounts
  AgentsDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: Ref DatabaseAgents

  Service:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Join: ['-', [Ref ServiceName, lambda, Ref Environment]]
      Role:
        Fn::GetAtt:
          - ServiceARN
          - Arn
      Runtime: go1.x
      Handler: Ref ServiceName
      Environment:
        DB_REGION: Ref AWS::Region
        DB_BUGS_TABLE: Ref DatabaseBugs
        DB_ACCOUNTS_TABLE: Ref DatabaseAccounts
        SQS_HOSTNAME: Ref MainQueue
      Code:
        S3Bucket: Ref BuildBucket
        S3Key: Ref BuildKey

Outputs:
  SourceQueueURL:
    Description: URL of the Main Queue
    Value:
      Ref: MainQueue
  SourceQueueARN:
    Description: ARN of the Main Queue
    Value:
        Fn::GetAtt:
          - MainQueue
          - Arn
  DeadLetterQueueURL:
    Description: URL of the Dead Letter Queue
    Value:
      Ref: DeadLetterQueue
  DeadLetterQueueARN:
    Description: ARN of the Dead Letter Queue
    Value:
      Fn::GetAtt:
        - DeadLetterQueue
        - Arn

