---
AWSTemplateFormatVersion: 2010-09-09
Description: Celeste Service

Parameters:
  ServiceName:
    Type: String
    Default: celeste
  Environment:
    Type: String
    Default: local

  RDSName:
    Type: String
    Default: bugfixes
  RDSInstanceClass:
    Type: String
    Default: db.m3.medium
  RDSAllocatedStorage:
    Type: String
    Default: "50"
  RDSUsername:
    Type: String
    Default: database_username
    NoEcho: true
  RDSPassword:
    Type: String
    Default: database_password
    NoEcho: true
  RDSHostname:
    Type: String
    Default: localhost
    NoEcho: true
  RDSPort:
    Type: Number
    Default: "5432"
    NoEcho: true

  DatabaseBugs:
    Type: String
    Default: bugs
  DatabaseAccounts:
    Type: String
    Default: accounts
  DatabaseAgents:
    Type: String
    Default: agents
  DatabaseComms:
    Type: String
    Default: comms
  DatabaseTicketing:
    Type: String
    Default: ticketing
  DatabaseTickets:
    Type: String
    Default: tickets
  DatabaseLogs:
    Type: String
    Default: logs

  LogQueueName:
    Type: String
    Default: logs
  BugQueueName:
    Type: String
    Default: bugs
  CommsQueueName:
    Type: String
    Default: comms
  TicketQueueName:
    Type: String
    Default: tickets

  BuildBucket:
    Type: String
    Default: bugfixes-celeste-builds
  BuildKey:
    Type: String
    Default: celeste-local.zip

  GithubKey:
    Type: String
  GithubSecret:
    Type: String
  GithubAppId:
    Type: String
  GoogleKey:
    Type: String
  GoogleSecret:
    Type: String

  JWTSecret:
    Type: String

Resources:
  ServiceARN:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'role'
          - !Ref Environment
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName:
            !Join
            - ''
            - - !Ref ServiceName
              - 'Lambda'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'sqs'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref BugQueue
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'sqs'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref LogQueue
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'sqs'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref TicketQueue
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'sqs'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref CommsQueue
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'sqs'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref BugQueueDeadLetter
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'sqs'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref LogQueueDeadLetter
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'sqs'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref TicketQueueDeadLetter
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'sqs'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref CommsQueueDeadLetter
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'dynamodb'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref DatabaseBugs
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'dynamodb'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref DatabaseAccounts
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'dynamodb'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref DatabaseAgents
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'dynamodb'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref DatabaseComms
              - Effect: Alow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'dynamodb'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref DatabaseTicketing
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'dynamodb'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref DatabaseTickets
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                  - dynamodb:DescribeTable
                Resource:
                  !Join
                  - ':'
                  - - 'arn'
                    - 'aws'
                    - 'dynamodb'
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Ref DatabaseLogs

  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'logs'
          - !Ref Environment
      RetentionInDays: 90

  BugQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt BugQueueDeadLetter.Arn
        maxReceiveCount: 5
      QueueName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'BugQueue'
          - !Ref Environment
  LogQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt LogQueueDeadLetter.Arn
        maxReceiveCount: 5
      QueueName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'LogQueue'
          - !Ref Environment
  TicketQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt TicketQueueDeadLetter.Arn
        maxReceiveCount: 5
      QueueName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'TicketQueue'
          - !Ref Environment
  CommsQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt CommsQueueDeadLetter.Arn
        maxReceiveCount: 5
      QueueName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'CommsQueue'
          - !Ref Environment
  BugQueueDeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'BugQueueDeadLetter'
          - !Ref Environment
  LogQueueDeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'LogQueueDeadLetter'
          - !Ref Environment
  TicketQueueDeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'TicketQueueDeadLetter'
          - !Ref Environment
  CommsQueueDeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        !Join
        - '-'
        - - !Ref ServiceName
          - 'CommsQueueDeadLetter'
          - !Ref Environment

  DynamoBugs:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DatabaseBugs
  DynamoAccounts:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DatabaseAccounts
  DynamoAgents:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DatabaseAgents
  DynamoComms:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DatabaseComms
  DynamoTicketing:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DatabaseTicketing
  DynamoTickets:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DatabaseTickets
  DynamoLogs:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DatabaseLogs

  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Join
        - '-'
        - - !Ref ServiceName
          - !Ref RDSName
          - !Ref Environment
      DBName: !Ref RDSName
      DBInstanceClass: !Ref RDSInstanceClass
      AllocatedStorage: !Ref RDSAllocatedStorage
      Engine: postgres
      MasterUsername: !Ref RDSUsername
      MasterUserPassword: !Ref RDSPassword
  RDSPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RDSPassword
      SecretString: !Ref RDSPassword
  RDSUsernameSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RDSUsername
      SecretString: !Ref RDSUsername
  RDSPortSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RDSPort
      SecretString: !Ref RDSPort
  RDSHostnameSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RDSHostname
      SecretString: !Ref RDSHostname
  RDSDatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RDSDatabase
      SecretString: !Ref RDSName

  ProvidersGithubKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: github_key
      SecretString: !Ref GithubKey
  ProvidersGithubSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: github_secret
      SecretString: !Ref GithubSecret
  ProvidersGithubAppId:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: github_app_id
      SecretString: !Ref GithubAppId
  ProvidersGoogleKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: google_key
      SecretString: !Ref GoogleKey
  ProvidersGoogleSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: google_secret
      SecretString: !Ref GoogleSecret

  JWT:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: jwt_secret
      SecretString: !Ref JWTSecret

  DockerRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: celeste
      RepositoryPolicyText:
        Version: 2012-10-17make
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principle:
              AWS: !Join
                - ':'
                - - 'arn'
                  - 'aws'
                  - 'iam'
                  - !Ref AWS::AccountId
                  - 'users/Keloran'
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: CelesteCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1


  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName:
        !Join
        - '-'
        - - 'bugfixes'
          - !Ref ServiceName
          - !Ref Environment

#  Gateway:
#    Type: AWS::ApiGateway::RestApi
#    Properties:
#      EndpointConfiguration:
#        Types:
#          - REGIONAL
#      Name:
#        !Join
#        - '-'
#        - - !Ref ServiceName
#          - 'Gateway'
#          - !Ref Environment
#  GatewayV1:
#    DependsOn:
#      - GatewayDeployment
#    Type: AWS::ApiGateway::Stage
#    Properties:
#      DeploymentId: !Ref GatewayDeployment
#      RestApiId: !Ref Gateway
#      StageName: 'v0'
#  GatewayDeployment:
#    Type: AWS::ApiGateway::Deployment
#    DependsOn:
#      - CreateAccount
#    Properties:
#      RestApiId: !Ref Gateway
#  GatewayEmptyModel:
#    Type: AWS::ApiGateway::Model
#    Properties:
#      ContentType: 'application/json'
#      RestApiId: !Ref Gateway
#      Schema: {}
#  CreateAccountResource:
#    DependsOn:
#      - GatewayEmptyModel
#      - CreateAccountRequestModel
#    Type: AWS::ApiGateway::Resource
#    Properties:
#      ParentId:
#        !GetAtt
#        - Gateway
#        - RootResourceId
#      PathPart: 'account'
#      RestApiId: !Ref Gateway
#  CreateAccountRequestModel:
#    DependsOn:
#      - Gateway
#    Type: AWS::ApiGateway::Model
#    Properties:
#      ContentType: 'application/json'
#      RestApiId: !Ref Gateway
#      Schema:
#        $schema: 'http://json-schema.org/draft-04/schema#'
#        title: AccountCreate
#        type: object
#        properties:
#          name:
#            type: string
#          email:
#            type: string
#            format: email
#  CreateAccount:
#    DependsOn:
#      - CreateAccountResource
#    Type: AWS::ApiGateway::Method
#    Properties:
#      ApiKeyRequired: false
#      AuthorizationType: NONE
#      HttpMethod: POST
#      Integration:
#        ConnectionType: INTERNET
#        IntegrationResponses:
#          - ResponseTemplates:
#              application/json: "{\"operation\":\"celeste_account_create\",\"data\":{\"key\":\"123e4567-e89b-12d3-a456-426614174000\",\"secret\":\"123e4567-e89b-12d3-a456-426614174000\"}}"
#            SelectionPattern: '2\d{2}'
#            StatusCode: '202'
#          - ResponseTemplates:
#              application/json: "{\"message\":\"Unknown Error\"}"
#            SelectionPattern: '5\d{2}'
#            StatusCode: '500'
#        PassthroughBehavior: WHEN_NO_TEMPLATES
#        RequestTemplates:
#          application/json: !Ref CreateAccountRequestModel
#        Type: MOCK
#        TimeoutInMillis: 29000
#      MethodResponses:
#        - ResponseModels:
#            application/json: !Ref GatewayEmptyModel
#          StatusCode: '202'
#        - ResponseModels:
#            application/json: !Ref GatewayEmptyModel
#          StatusCode: '500'
#      OperationName: 'create_account'
#      ResourceId: !Ref CreateAccountResource
#      RestApiId: !Ref Gateway


# RestApi -> Empty Model -> Create Account Resource -> Create Account Method -> Deployment -> stage
