version: '3.9'

services:
    localstack:
      image: localstack/localstack:latest
      ports:
        - 53:53
        - 443:443
        - 4510-4530:4510-4530
        - 4566-4620:4566-4620
      environment:
        - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
    database:
      image: postgres:13
      restart: always
      environment:
        POSTGRES_PASSWORD: database_password
        POSTGRES_USER: database_username
        POSTGRES_DB: bugfixes
      ports:
        - 5432:5432

