// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	comms "github.com/bugfixes/celeste/internal/comms"
	mock "github.com/stretchr/testify/mock"
)

// CommsSystem is an autogenerated mock type for the CommsSystem type
type CommsSystem struct {
	mock.Mock
}

// Connect provides a mock function with given fields:
func (_m *CommsSystem) Connect() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParseCredentials provides a mock function with given fields: _a0
func (_m *CommsSystem) ParseCredentials(_a0 interface{}) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: cp
func (_m *CommsSystem) Send(cp comms.CommsPackage) error {
	ret := _m.Called(cp)

	var r0 error
	if rf, ok := ret.Get(0).(func(comms.CommsPackage) error); ok {
		r0 = rf(cp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
