// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	comms "github.com/bugfixes/celeste/internal/comms"
	mock "github.com/stretchr/testify/mock"
)

// Comms is an autogenerated mock type for the Comms type
type Comms struct {
	mock.Mock
}

// Send provides a mock function with given fields: cp
func (_m *Comms) Send(cp comms.CommsPackage) (comms.AckPackage, error) {
	ret := _m.Called(cp)

	var r0 comms.AckPackage
	if rf, ok := ret.Get(0).(func(comms.CommsPackage) comms.AckPackage); ok {
		r0 = rf(cp)
	} else {
		r0 = ret.Get(0).(comms.AckPackage)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(comms.CommsPackage) error); ok {
		r1 = rf(cp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
