// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	agent "github.com/bugfixes/celeste/internal/celeste/agent"
	mock "github.com/stretchr/testify/mock"
)

// Agents is an autogenerated mock type for the Agents type
type Agents struct {
	mock.Mock
}

// Create provides a mock function with given fields:
func (_m *Agents) Create() (*agent.Agent, error) {
	ret := _m.Called()

	var r0 *agent.Agent
	if rf, ok := ret.Get(0).(func() *agent.Agent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent.Agent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: a
func (_m *Agents) Delete(a agent.Agent) error {
	ret := _m.Called(a)

	var r0 error
	if rf, ok := ret.Get(0).(func(agent.Agent) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
