name: Auto Merge
on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Pull Requests'

jobs:
  auto-merge:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4.0
        with:
          github-token: ${{ secrets.GH_SECRET }}
