name: Branch
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --config ./configs/golangci.yml

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install deps
        run: pip install wheel setuptools --upgrade
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: bob
          aws-secret-access-key: bob
      - name: localstack
        run: make cloud-up
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
      - name: test
        run: go test -v -race -bench=./... -benchmem -timeout=120s -bench=./... ./...
