name: Deploybot
on:
  push:
    branches:
      - '!main'
      - '*'
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --config ./configs/golangci.yml

  automerge:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/actions-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
