name: Deploybot
on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - opened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --config ./configs/golangci.yml

  automerge:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
