name: Master
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: install golang-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: test
        run: go test -v -race -bench=./... -benchmem -timeout=120s -bench=./... ./...
